# Generated by Django 6.1 on 2026-09-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aquecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("marca", models.CharField(blank=True, max_length=100)),
                ("modelo", models.CharField(blank=True, max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("filtro", "Filtro"),
                            ("aquecedor", "Aquecedor"),
                            ("iluminacao", "Iluminação"),
                            ("co2", "Sistema de CO2"),
                            ("substrato", "Substrato"),
                            ("bomba", "Bomba/Circulador"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="equipamentos/"),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "litros_min_indicado",
                    models.PositiveIntegerField(
                        help_text="Litragem minime=a recomendada", null=True
                    ),
                ),
                (
                    "litros_max_indicado",
                    models.PositiveIntegerField(
                        blank=True, help_text="Litragem máxima recomendada", null=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("potencia_watts", models.PositiveIntegerField()),
                (
                    "temp_min_ajustavel",
                    models.DecimalField(decimal_places=1, default=20.0, max_digits=4),
                ),
                (
                    "temp_max_ajustavel",
                    models.DecimalField(decimal_places=1, default=30.0, max_digits=4),
                ),
                ("termostato_integrado", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Aquecedor",
                "verbose_name_plural": "Aquecedores",
            },
        ),
        migrations.CreateModel(
            name="BombaCirculadora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("marca", models.CharField(blank=True, max_length=100)),
                ("modelo", models.CharField(blank=True, max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("filtro", "Filtro"),
                            ("aquecedor", "Aquecedor"),
                            ("iluminacao", "Iluminação"),
                            ("co2", "Sistema de CO2"),
                            ("substrato", "Substrato"),
                            ("bomba", "Bomba/Circulador"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="equipamentos/"),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "litros_min_indicado",
                    models.PositiveIntegerField(
                        help_text="Litragem minime=a recomendada", null=True
                    ),
                ),
                (
                    "litros_max_indicado",
                    models.PositiveIntegerField(
                        blank=True, help_text="Litragem máxima recomendada", null=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "vazao_lh",
                    models.PositiveIntegerField(
                        help_text="Vazão em litros por hora (L/h)"
                    ),
                ),
                ("ajustavel", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Bomba/Circulador",
                "verbose_name_plural": "Bombas/Circuladores",
            },
        ),
        migrations.CreateModel(
            name="Filtro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("marca", models.CharField(blank=True, max_length=100)),
                ("modelo", models.CharField(blank=True, max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("filtro", "Filtro"),
                            ("aquecedor", "Aquecedor"),
                            ("iluminacao", "Iluminação"),
                            ("co2", "Sistema de CO2"),
                            ("substrato", "Substrato"),
                            ("bomba", "Bomba/Circulador"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="equipamentos/"),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "litros_min_indicado",
                    models.PositiveIntegerField(
                        help_text="Litragem minime=a recomendada", null=True
                    ),
                ),
                (
                    "litros_max_indicado",
                    models.PositiveIntegerField(
                        blank=True, help_text="Litragem máxima recomendada", null=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo_filtro",
                    models.CharField(
                        choices=[
                            ("interno", "Interno"),
                            ("externo", "Externo (HOB)"),
                            ("canister", "Canister"),
                            ("mochila", "Mochila"),
                            ("sump", "Sump"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "vazao_lh",
                    models.PositiveIntegerField(
                        help_text="Vazão em litro por hora (L/h)"
                    ),
                ),
                (
                    "numero_estagios",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Nº de estágios de filtragem (mecânica/biológica/química)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filtro",
                "verbose_name_plural": "Filtros",
            },
        ),
        migrations.CreateModel(
            name="Iluminacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("marca", models.CharField(blank=True, max_length=100)),
                ("modelo", models.CharField(blank=True, max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("filtro", "Filtro"),
                            ("aquecedor", "Aquecedor"),
                            ("iluminacao", "Iluminação"),
                            ("co2", "Sistema de CO2"),
                            ("substrato", "Substrato"),
                            ("bomba", "Bomba/Circulador"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="equipamentos/"),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "litros_min_indicado",
                    models.PositiveIntegerField(
                        help_text="Litragem minime=a recomendada", null=True
                    ),
                ),
                (
                    "litros_max_indicado",
                    models.PositiveIntegerField(
                        blank=True, help_text="Litragem máxima recomendada", null=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("potencia_watts", models.PositiveIntegerField(blank=True, null=True)),
                ("lumens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "par_a_30cm",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="\n            PAR medido a 30cm da superfície — referência p/\n            necessidade de luz das plantas\n        ",
                        null=True,
                    ),
                ),
                (
                    "espectro_kelvin",
                    models.PositiveIntegerField(
                        blank=True, help_text="Temperatura de cor em Kelvin", null=True
                    ),
                ),
                (
                    "comprimento_cm",
                    models.PositiveIntegerField(
                        blank=True, help_text="Comprimento da luminária", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Iluminação",
                "verbose_name_plural": "Iluminações",
            },
        ),
        migrations.CreateModel(
            name="SistemaCO2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("marca", models.CharField(blank=True, max_length=100)),
                ("modelo", models.CharField(blank=True, max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("filtro", "Filtro"),
                            ("aquecedor", "Aquecedor"),
                            ("iluminacao", "Iluminação"),
                            ("co2", "Sistema de CO2"),
                            ("substrato", "Substrato"),
                            ("bomba", "Bomba/Circulador"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="equipamentos/"),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "litros_min_indicado",
                    models.PositiveIntegerField(
                        help_text="Litragem minime=a recomendada", null=True
                    ),
                ),
                (
                    "litros_max_indicado",
                    models.PositiveIntegerField(
                        blank=True, help_text="Litragem máxima recomendada", null=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo_co2",
                    models.CharField(
                        choices=[
                            ("pressurizado", "Pressurizado"),
                            ("diy", "DIY (fermentação)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "vazao_bps",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Vazão em bolhas por segundo (BPS) recomendada",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("possui_difusor", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Sistema de CO2",
                "verbose_name_plural": "Sistemas de CO2",
            },
        ),
        migrations.CreateModel(
            name="Substrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("marca", models.CharField(blank=True, max_length=100)),
                ("modelo", models.CharField(blank=True, max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("filtro", "Filtro"),
                            ("aquecedor", "Aquecedor"),
                            ("iluminacao", "Iluminação"),
                            ("co2", "Sistema de CO2"),
                            ("substrato", "Substrato"),
                            ("bomba", "Bomba/Circulador"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="equipamentos/"),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "litros_min_indicado",
                    models.PositiveIntegerField(
                        help_text="Litragem minime=a recomendada", null=True
                    ),
                ),
                (
                    "litros_max_indicado",
                    models.PositiveIntegerField(
                        blank=True, help_text="Litragem máxima recomendada", null=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo_substrato",
                    models.CharField(
                        choices=[
                            ("inerte", "Inerte (areia, cascalho)"),
                            ("nutritivo", "Nutritivo/Fértil"),
                            ("solo_ativo", "Solo ativo (reduz pH/GH)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("altera_ph", models.BooleanField(default=False)),
                ("altera_gh", models.BooleanField(default=False)),
                (
                    "granulometria_mm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Substrato",
                "verbose_name_plural": "Substratos",
            },
        ),
    ]
