# Generated by Django 6.1 on 2026-09-09 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipamentos", "0001_initial"),
        ("especies", "0002_alter_fauna_tipo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aquario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: 'Aquário da sala', 'Betta solo'", max_length=150
                    ),
                ),
                (
                    "litros",
                    models.PositiveIntegerField(help_text="Volumne total em litros"),
                ),
                ("comprimento_cm", models.PositiveIntegerField(blank=True, null=True)),
                ("largura_cm", models.PositiveIntegerField(blank=True, null=True)),
                ("altura_cm", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ph_atual",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "temp_atual",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "gh_atual",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "publico",
                    models.BooleanField(
                        default=False,
                        help_text="Se True, outros usuários podem ver este aquário",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aquarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Aquário",
                "verbose_name_plural": "Aquários",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="AquarioEquipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("filtro", "Filtro"),
                            ("aquecedor", "Aquecedor"),
                            ("iluminacao", "Iluminação"),
                            ("co2", "Sistema de CO2"),
                            ("substrato", "Substrato"),
                            ("bomba", "Bomba/Circulador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("equipamento_id", models.PositiveIntegerField()),
                ("ativo", models.BooleanField(default=True)),
                ("adicionado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "aquario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_equipamento",
                        to="equipamentos.aquario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipamento do Aquário",
                "verbose_name_plural": "Equipamentos dos Aquários",
                "unique_together": {("aquario", "categoria", "equipamento_id")},
            },
        ),
        migrations.CreateModel(
            name="AquarioFauna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("adicionado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "aquario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_fauna",
                        to="equipamentos.aquario",
                    ),
                ),
                (
                    "fauna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="em_aquarios",
                        to="especies.fauna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fauna do Aquário",
                "verbose_name_plural": "Fauna dos Aquários",
                "unique_together": {("aquario", "fauna")},
            },
        ),
        migrations.CreateModel(
            name="AquarioFlora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("adicionado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "aquario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_flora",
                        to="equipamentos.aquario",
                    ),
                ),
                (
                    "flora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="em_aquarios",
                        to="especies.flora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flora do Aquário",
                "verbose_name_plural": "Flora dos Aquários",
                "unique_together": {("aquario", "flora")},
            },
        ),
    ]
