# Generated by Django 6.1 on 2026-09-01 10:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Familia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_cientifico", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Família",
                "verbose_name_plural": "Famílias",
                "ordering": ["nome_cientifico"],
            },
        ),
        migrations.CreateModel(
            name="GrupoComercial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Grupo Comercial",
                "verbose_name_plural": "Grupos Comerciais",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_cientifico", models.CharField(max_length=100)),
                (
                    "familia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generos",
                        to="especies.familia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gênero",
                "verbose_name_plural": "Gêneros",
                "ordering": ["nome_cientifico"],
                "unique_together": {("familia", "nome_cientifico")},
            },
        ),
        migrations.CreateModel(
            name="Flora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "epiteto_especifico",
                    models.CharField(
                        help_text="Segunda parte do nome científico.\n        Ex: em 'Paracheirodon innesi', digite apenas 'innesi'.",
                        max_length=100,
                    ),
                ),
                ("nome_popular", models.CharField(max_length=150)),
                (
                    "origem",
                    models.CharField(
                        blank=True, help_text="Região de origem natural", max_length=150
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="organismos/"),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "ph_min",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ],
                    ),
                ),
                (
                    "ph_max",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ],
                    ),
                ),
                (
                    "temp_min",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Temperatura mínima em °C",
                        max_digits=4,
                    ),
                ),
                (
                    "temp_max",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Temperatura máxima em °C",
                        max_digits=4,
                    ),
                ),
                (
                    "gh_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Dureza mínima (GH)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "gh_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Dureza máxima (GH)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "observacoes_compatibilidade",
                    models.JSONField(blank=True, default=dict),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "necessidade_luz",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("necessidade_co2", models.BooleanField(default=False)),
                (
                    "velocidade_crescimento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lenta", "Lenta"),
                            ("media", "Média"),
                            ("rapida", "Rápida"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "posicao_plantio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fundo", "Fundo"),
                            ("meio", "Meio/Plano médio"),
                            ("flutuante", "Flutuante"),
                            ("epifita", "Epífita"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sensivel_a_herbivoros",
                    models.BooleanField(
                        default=False,
                        help_text="Se True, conflita com Fauna que come_plantas",
                    ),
                ),
                (
                    "genero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="especies.genero",
                    ),
                ),
                (
                    "grupo_comercial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to="especies.grupocomercial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flora",
                "verbose_name_plural": "Flora",
                "ordering": ["nome_popular"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Fauna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "epiteto_especifico",
                    models.CharField(
                        help_text="Segunda parte do nome científico.\n        Ex: em 'Paracheirodon innesi', digite apenas 'innesi'.",
                        max_length=100,
                    ),
                ),
                ("nome_popular", models.CharField(max_length=150)),
                (
                    "origem",
                    models.CharField(
                        blank=True, help_text="Região de origem natural", max_length=150
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="organismos/"),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "ph_min",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ],
                    ),
                ),
                (
                    "ph_max",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ],
                    ),
                ),
                (
                    "temp_min",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Temperatura mínima em °C",
                        max_digits=4,
                    ),
                ),
                (
                    "temp_max",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Temperatura máxima em °C",
                        max_digits=4,
                    ),
                ),
                (
                    "gh_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Dureza mínima (GH)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "gh_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Dureza máxima (GH)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "observacoes_compatibilidade",
                    models.JSONField(blank=True, default=dict),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("peixe", "Peixe"),
                            ("invertebrado", "Invertebrado"),
                            ("coral", "Coral"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "temperamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pacifico", "Pacifico"),
                            ("semi_agressivo", "Semi-agressivo"),
                            ("agressivo", "Agressivo"),
                            ("territorial", "Territorial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tamanho_adulto_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "litragem_minima",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Litragem minima recomendada por individuo/grupo",
                        null=True,
                    ),
                ),
                (
                    "nivel_agua",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fundo", "Fundo"),
                            ("meio", "Meio"),
                            ("superficie", "Superfície"),
                            ("todos", "Todos os níveis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dieta",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("herbivoro", "Herbívoro"),
                            ("carnivoro", "Carnívoro"),
                            ("onivoro", "Onívoro"),
                            ("filtrador", "Filtrador"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "comportamento_social",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("solitario", "Solitário"),
                            ("casal", "Casal"),
                            ("cardume", "Cardume"),
                            ("colonia", "Colônia"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tamanho_minimo_grupo",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ex: cardume mínimo de 6 indivíduos",
                        null=True,
                    ),
                ),
                (
                    "come_plantas",
                    models.BooleanField(
                        default=False,
                        help_text="Se True, entra em conflito automático com Flora sensível",
                    ),
                ),
                (
                    "genero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="especies.genero",
                    ),
                ),
                (
                    "grupo_comercial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to="especies.grupocomercial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fauna",
                "verbose_name_plural": "Fauna",
                "ordering": ["nome_popular"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegraCompatibilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_a",
                    models.CharField(
                        choices=[("fauna", "Fauna"), ("flora", "Flora")], max_length=10
                    ),
                ),
                ("id_a", models.PositiveIntegerField()),
                (
                    "tipo_b",
                    models.CharField(
                        choices=[("fauna", "Fauna"), ("flora", "Flora")], max_length=10
                    ),
                ),
                ("id_b", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compativel", "Compatível"),
                            ("ressalvas", "Compatível com ressalvas"),
                            ("incompativel", "Incompatível"),
                        ],
                        max_length=20,
                    ),
                ),
                ("justificativa", models.TextField()),
            ],
            options={
                "verbose_name": "Regra de Compatibilidade",
                "verbose_name_plural": "Regras de Compatibilidade",
                "unique_together": {("tipo_a", "id_a", "tipo_b", "id_b")},
            },
        ),
    ]
