# Generated by Django 6.1 on 2026-09-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("especies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fauna",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("peixe", "Peixe"),
                    ("invertebrado", "Invertebrado"),
                    ("coral", "Coral"),
                    ("anfibio", "Anfibio"),
                    ("reptil", "Reptil"),
                ],
                max_length=20,
            ),
        ),
    ]
