# Generated by Django 6.1 on 2026-10-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("especies", "0002_alter_fauna_tipo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flora",
            name="genero",
        ),
        migrations.RemoveField(
            model_name="flora",
            name="grupo_comercial",
        ),
    ]
