# Generated by Django 6.1 on 2026-10-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("especies", "0003_remove_flora_genero_remove_flora_grupo_comercial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneroFlora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_cientifico", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Gênero Flora",
                "verbose_name_plural": "Gêneros Floras",
                "ordering": ["nome_cientifico"],
            },
        ),
    ]
