# Generated by Django 6.1 on 2026-10-06 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("especies", "0004_generoflora"),
    ]

    operations = [
        migrations.AddField(
            model_name="flora",
            name="genero",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_set",
                to="especies.generoflora",
            ),
            preserve_default=False,
        ),
    ]
