# Generated by Django 6.1 on 2026-10-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("especies", "0005_flora_genero"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generoflora",
            options={
                "ordering": ["nome"],
                "verbose_name": "Gênero Flora",
                "verbose_name_plural": "Gêneros Floras",
            },
        ),
        migrations.RenameField(
            model_name="generoflora",
            old_name="nome_cientifico",
            new_name="nome",
        ),
        migrations.AddField(
            model_name="generoflora",
            name="descricao",
            field=models.TextField(blank=True),
        ),
    ]
